# Generated by Django 4.2.20 on 2025-04-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1_organization', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationType',
        ),
    ]
