# Generated by Django 4.2.20 on 2025-05-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_v1_organization", "0002_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="language",
            field=models.CharField(
                blank=True,
                default="en",
                help_text="Default language preference",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="UTC",
                help_text="Default timezone for the organization",
                max_length=50,
                null=True,
            ),
        ),
    ]
