# Generated by Django 4.2.20 on 2025-05-03 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("contact", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_v1_organization", "0002_create_initial_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="primary_contact",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary contact person for the organization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_for_organizations",
                to="contact.contact",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated the record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationmembership",
            unique_together={("user", "organization")},
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["name"], name="api_v1_orga_name_8ebb11_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["status"], name="api_v1_orga_status_255b9b_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["code"], name="api_v1_orga_code_147d61_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["organization_type"], name="api_v1_orga_organiz_5ade16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["user", "organization"], name="api_v1_orga_user_id_9bfba2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(fields=["role"], name="api_v1_orga_role_id_660bea_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["is_active"], name="api_v1_orga_is_acti_c569a4_idx"
            ),
        ),
    ]
