# Generated by Django 4.2.20 on 2025-05-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "api_v1_organization",
            "0003_organization_primary_contact_organization_tags_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="organizationmembership",
            name="api_v1_orga_role_id_660bea_idx",
        ),
        migrations.RemoveField(
            model_name="organizationmembership",
            name="role",
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="organization_memberships",
                to="auth.group",
                verbose_name="Roles (Groups)",
            ),
        ),
    ]
