# Generated by Django 4.2.20 on 2025-05-02 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("api_v1_organization", "0004_organizationmembership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationmembership",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_memberships",
                to="auth.group",
                verbose_name="Role (Group)",
            ),
        ),
    ]
