# Generated by Django 4.2.20 on 2025-05-06 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("file_storage", "0001_initial"),
        (
            "api_v1_organization",
            "0004_remove_organizationmembership_api_v1_orga_role_id_660bea_idx_and_more",
        ),
        ("taggit", "0005_auto_20220424_2025"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_v1_category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text="Primary display name or title of the document.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("pending_review", "Pending Review"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Status of the document.",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Simple integer representing the document version number.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or summary.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores values for dynamically defined custom fields relevant to the document.",
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the related business entity.",
                        max_length=255,
                        null=True,
                        verbose_name="Related Object ID",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Content type of the related business entity.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Related Object Type",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Classification using the generic Category model.",
                        limit_choices_to={"category_type": "DOCUMENT_TYPE"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="typed_documents",
                        to="api_v1_category.category",
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        help_text="Links to the metadata record of the actual underlying file content.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="file_storage.filestorage",
                        verbose_name="File",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The Organization this record belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="api_v1_organization.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="For flexible classification.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated the record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_version_document", "Can create new versions of a document")
                ],
                "indexes": [
                    models.Index(
                        fields=["document_type"], name="documents_d_documen_cea4b4_idx"
                    ),
                    models.Index(
                        fields=["status"], name="documents_d_status_07369e_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="documents_d_content_ba3031_idx",
                    ),
                ],
            },
        ),
    ]
