# Generated by Django 4.2.20 on 2025-04-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the feature flag.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Description of what this flag controls.', verbose_name='Description')),
                ('enabled', models.BooleanField(default=False, help_text='Whether this flag is currently enabled.', verbose_name='Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this flag was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this flag was last updated.', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Flag',
                'verbose_name_plural': 'Flags',
                'ordering': ['name'],
            },
        ),
    ]
