# Generated by Django 4.2.20 on 2025-04-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20250427_0604"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Flag",
        ),
    ]
