# Generated by Django 4.2.20 on 2025-04-27 23:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_recreate_flag_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Flag",
        ),
    ]
