# Generated by Django 4.2.20 on 2025-04-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250426_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestAuditableModel',
        ),
    ]
