# Generated by Django 4.2.20 on 2025-05-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_v1_common", "0002_populate_initial_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="category",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Optional category for grouping statuses (e.g., 'General', 'Order Lifecycle').",
                max_length=50,
                null=True,
                verbose_name="Category",
            ),
        ),
    ]
