# Generated by Django 4.2.20 on 2025-05-06 03:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_v1_common", "0005_populate_initial_uom"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Status",
        ),
    ]
