# Generated by Django 4.2.20 on 2025-05-03 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "api_v1_organization",
            "0003_organization_primary_contact_organization_tags_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN_SUCCESS", "Login Success"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("LOGOUT", "Logout"),
                            ("PERMISSION_ASSIGN", "Permission Assigned"),
                            ("PERMISSION_REVOKE", "Permission Revoked"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Action Type",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Primary key of the object as string.",
                        max_length=255,
                        null=True,
                        verbose_name="Object ID",
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        help_text="A human-readable representation of the object.",
                        max_length=255,
                        verbose_name="Object Representation",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="JSON detailing field changes for UPDATE actions (e.g., {'field': {'old': 'val1', 'new': 'val2'}}).",
                        null=True,
                        verbose_name="Changes",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Additional context (e.g., IP address, session key).",
                        null=True,
                        verbose_name="Context",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Content Type",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api_v1_organization.organization",
                        verbose_name="Organization Context",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Log Entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_audit_content_4c2ead_idx",
                    ),
                    models.Index(
                        fields=["organization", "user"],
                        name="audit_audit_organiz_6f2ad4_idx",
                    ),
                    models.Index(
                        fields=["action_type"], name="audit_audit_action__dd3a3c_idx"
                    ),
                ],
            },
        ),
    ]
