# Generated by Django 4.2.20 on 2025-05-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAILED", "Login Failed"),
                    ("LOGOUT", "Logout"),
                    ("PERMISSION_ASSIGN", "Permission Assigned"),
                    ("PERMISSION_REVOKE", "Permission Revoked"),
                    ("SYSTEM_EVENT", "System Event"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="Action Type",
            ),
        ),
    ]
