# Generated by Django 4.2.20 on 2025-05-03 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "api_v1_organization",
            "0003_organization_primary_contact_organization_tags_and_more",
        ),
        ("audit", "0002_alter_auditlog_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="api_v1_organization.organization",
                verbose_name="Organization Context",
            ),
        ),
    ]
