# Generated by Django 4.2.20 on 2025-05-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api_v1_organization", "0005_alter_organizationmembership_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcreteScopedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The Organization this record belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="api_v1_organization.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concrete Test Model (Scoped)",
            },
        ),
    ]
