# Generated by Django 4.2.20 on 2025-05-04 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "api_v1_organization",
            "0003_organization_primary_contact_organization_tags_and_more",
        ),
        ("core_tests_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MockOrgScopedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_scoped_items",
                        to="api_v1_organization.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mock Organization Scoped Model",
                "verbose_name_plural": "Mock Organization Scoped Models",
            },
        ),
    ]
