import factory
from factory.django import DjangoModelFactory
from taggit.models import Tag

class TagFactory(DjangoModelFactory):
    """
    Factory for creating Tag instances.
    Note that the Tag model is from django-taggit and is not organization-scoped.
    """
    class Meta:
        model = Tag
        django_get_or_create = ('name',)  # Use name for uniqueness

    name = factory.Sequence(lambda n: f'Common Tag {n}')
    # slug is auto-generated by taggit 