import factory
from factory.django import DjangoModelFactory
from taggit.models import Tag # Using default Tag model

class TagFactory(DjangoModelFactory):
    class Meta:
        model = Tag
        django_get_or_create = ('name',) # Use name for uniqueness

    name = factory.Sequence(lambda n: f'Common Tag {n}')
    # slug is auto-generated by taggit 