# Generated by Django 4.2.20 on 2025-05-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactphonenumber",
            name="phone_number",
            field=models.CharField(max_length=50, verbose_name="Phone Number"),
        ),
    ]
