# Generated by Django 4.2.20 on 2025-05-01 01:46

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("address", "0004_alter_address_created_by_alter_address_updated_by"),
        ("contact", "0002_alter_contactphonenumber_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactaddress",
            options={
                "ordering": ["-is_primary", "created_at"],
                "verbose_name": "Contact Address",
                "verbose_name_plural": "Contact Addresses",
            },
        ),
        migrations.AlterModelOptions(
            name="contactemailaddress",
            options={
                "ordering": ["-is_primary", "created_at"],
                "verbose_name": "Contact Email Address",
                "verbose_name_plural": "Contact Email Addresses",
            },
        ),
        migrations.AlterModelOptions(
            name="contactphonenumber",
            options={
                "ordering": ["-is_primary", "created_at"],
                "verbose_name": "Contact Phone Number",
                "verbose_name_plural": "Contact Phone Numbers",
            },
        ),
        migrations.AddField(
            model_name="contactaddress",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about this address",
                verbose_name="Notes",
            ),
        ),
        migrations.AddField(
            model_name="contactemailaddress",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about this email address",
                verbose_name="Notes",
            ),
        ),
        migrations.AddField(
            model_name="contactphonenumber",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about this phone number",
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("billing", "Billing"),
                    ("support", "Support"),
                    ("technical", "Technical"),
                    ("other", "Other"),
                ],
                default="primary",
                help_text="Type of contact (e.g., individual, business)",
                max_length=20,
                verbose_name="Contact Type",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="custom_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional custom fields for the contact",
                verbose_name="Custom Fields",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(
                help_text="First name of the contact",
                max_length=100,
                verbose_name="First Name",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(
                help_text="Last name of the contact",
                max_length=100,
                verbose_name="Last Name",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about the contact",
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="organization_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID of the linked organization (temporary field)",
                null=True,
                verbose_name="Organization ID",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="organization_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the organization if not linked to an existing one",
                max_length=200,
                verbose_name="Organization Name",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="source",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("referral", "Referral"),
                    ("conference", "Conference"),
                    ("other", "Other"),
                ],
                default="website",
                help_text="How the contact was acquired",
                max_length=20,
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("do_not_contact", "Do Not Contact"),
                ],
                default="active",
                help_text="Current status of the contact",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Tags associated with this contact",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Professional title or position",
                max_length=100,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="contactaddress",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contact_addresses",
                to="address.address",
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="contactaddress",
            name="address_type",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("work", "Work"),
                    ("billing", "Billing"),
                    ("shipping", "Shipping"),
                    ("other", "Other"),
                ],
                default="home",
                help_text="The type of address (e.g., home, work)",
                max_length=20,
                verbose_name="Address Type",
            ),
        ),
        migrations.AlterField(
            model_name="contactaddress",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is the primary address for the contact",
                verbose_name="Is Primary",
            ),
        ),
        migrations.AlterField(
            model_name="contactemailaddress",
            name="email",
            field=models.EmailField(
                help_text="The email address",
                max_length=254,
                verbose_name="Email Address",
            ),
        ),
        migrations.AlterField(
            model_name="contactemailaddress",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("work", "Work"),
                    ("personal", "Personal"),
                    ("other", "Other"),
                ],
                default="personal",
                help_text="The type of email address (e.g., personal, work)",
                max_length=20,
                verbose_name="Email Type",
            ),
        ),
        migrations.AlterField(
            model_name="contactemailaddress",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is the primary email address for the contact",
                verbose_name="Is Primary",
            ),
        ),
        migrations.AlterField(
            model_name="contactphonenumber",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is the primary phone number for the contact",
                verbose_name="Is Primary",
            ),
        ),
        migrations.AlterField(
            model_name="contactphonenumber",
            name="phone_number",
            field=models.CharField(
                help_text="The phone number in E.164 format (e.g., +12125551234)",
                max_length=50,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="contactphonenumber",
            name="phone_type",
            field=models.CharField(
                choices=[
                    ("mobile", "Mobile"),
                    ("work", "Work"),
                    ("home", "Home"),
                    ("fax", "Fax"),
                    ("other", "Other"),
                ],
                default="mobile",
                help_text="The type of phone number (e.g., mobile, work, home)",
                max_length=20,
                verbose_name="Phone Type",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contactaddress",
            unique_together={("contact", "address")},
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["source"], name="contact_con_source_159e49_idx"),
        ),
    ]
