# Generated by Django 4.2.20 on 2025-05-01 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api_v1_organization", "0002_organization"),
        ("contact", "0003_alter_contactaddress_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="organization_id",
        ),
        migrations.AddField(
            model_name="contact",
            name="linked_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization this contact is linked to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts",
                to="api_v1_organization.organization",
                verbose_name="Linked Organization",
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["linked_organization"], name="contact_con_linked__9df5eb_idx"
            ),
        ),
    ]
