# Generated by Django 4.2.20 on 2025-05-06 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api_v1_category", "0001_initial"),
        ("api_v1_status", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional category for grouping statuses.",
                limit_choices_to={"category_type": "OTHER"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="statuses",
                to="api_v1_category.category",
                verbose_name="Category",
            ),
        ),
    ]
