# Generated by Django 5.2 on 2025-04-26 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated.', verbose_name='Updated At')),
                ('code', models.CharField(help_text='ISO 4217 3-letter currency code.', max_length=3, primary_key=True, serialize=False, verbose_name='ISO 4217 Code')),
                ('name', models.CharField(db_index=True, help_text='Official name of the currency.', max_length=100, unique=True, verbose_name='Name')),
                ('symbol', models.CharField(blank=True, help_text='Common symbol for the currency (e.g., $, €).', max_length=5, verbose_name='Symbol')),
                ('numeric_code', models.CharField(blank=True, db_index=True, help_text='ISO 4217 3-digit numeric currency code.', max_length=3, null=True, unique=True, verbose_name='ISO 4217 Numeric Code')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, help_text='Number of decimal places commonly used.', verbose_name='Decimal Places')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this currency available for use?', verbose_name='Is Active')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Custom data associated with this currency.', verbose_name='Custom Fields')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
    ]
