from rest_framework import serializers
from taggit.models import Tag


class TagSerializer(serializers.ModelSerializer):
    """
    Serializer for the django-taggit Tag model.
    This serializer doesn't require an organization field as tags are global.
    """
    class Meta:
        model = Tag
        fields = ['id', 'name', 'slug']
        read_only_fields = ['slug']  # slug is auto-generated by taggit 