# Generated by Django 4.2.20 on 2025-05-06 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api_v1_category", "0001_initial"),
        ("taggit", "0005_auto_20220424_2025"),
        ("api_v1_common", "0006_delete_status"),
        (
            "api_v1_organization",
            "0004_remove_organizationmembership_api_v1_orga_role_id_660bea_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("PHYSICAL", "Physical Product"),
                            ("SERVICE", "Service"),
                            ("DIGITAL", "Digital Product"),
                            ("SUBSCRIPTION", "Subscription"),
                        ],
                        default="PHYSICAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("DISCONTINUED", "Discontinued"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_inventory_tracked", models.BooleanField(default=False)),
                ("is_purchasable", models.BooleanField(default=False)),
                ("is_sellable", models.BooleanField(default=False)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "base_uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="api_v1_common.unitofmeasure",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category_type": "PRODUCT"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="api_v1_category.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The Organization this record belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="api_v1_organization.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated the record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "permissions": [],
                "unique_together": {("organization", "sku")},
            },
        ),
    ]
