# Generated by Django 4.2.20 on 2025-04-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1_address', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='address',
            new_name='api_v1_addr_country_6e7734_idx',
            old_name='api_v1_comm_country_c8c0f4_idx',
        ),
    ]
