# Generated by Django 4.2.20 on 2025-04-27 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "CREATE INDEX IF NOT EXISTS api_v1_comm_country_c8c0f4_idx ON address_address (country);",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS api_v1_comm_country_c8c0f4_idx;",
            ],
        ),
    ]
