# Generated by Django 4.2.20 on 2025-04-27 23:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0002_auto_20250427_0709"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="address",
            new_name="address_add_country_ba8b5a_idx",
            old_name="api_v1_comm_country_c8c0f4_idx",
        ),
    ]
