# Generated by Django 4.2.20 on 2025-04-28 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "address",
            "0003_rename_api_v1_comm_country_c8c0f4_idx_address_add_country_ba8b5a_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated the record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
    ]
