# Generated by Django 4.2.20 on 2025-05-06 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taxes", "0002_taxcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the tax rate (e.g., 'CA State Sales Tax')",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Tax rate as a decimal (e.g., 0.0825 for 8.25%)",
                        max_digits=10,
                        verbose_name="Rate",
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("VAT", "Value Added Tax"),
                            ("GST", "Goods and Services Tax"),
                            ("SALES", "Sales Tax"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        help_text="The type of tax (VAT, GST, Sales, etc.)",
                        max_length=10,
                        verbose_name="Tax Type",
                    ),
                ),
                (
                    "is_compound",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this tax is applied after other taxes",
                        verbose_name="Is Compound",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Apply lower priorities first for compounding",
                        verbose_name="Priority",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Start date when this tax rate is valid",
                        null=True,
                        verbose_name="Valid From",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="End date when this tax rate expires",
                        null=True,
                        verbose_name="Valid To",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this tax rate is currently active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional custom fields for extensibility",
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "jurisdiction",
                    models.ForeignKey(
                        help_text="The jurisdiction where this tax rate applies",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxes.taxjurisdiction",
                        verbose_name="Jurisdiction",
                    ),
                ),
                (
                    "tax_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="The category of tax (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxes.taxcategory",
                        verbose_name="Tax Category",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated the record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Rate",
                "verbose_name_plural": "Tax Rates",
                "ordering": ["jurisdiction__code", "priority", "-valid_from"],
                "indexes": [
                    models.Index(
                        fields=[
                            "jurisdiction",
                            "tax_category",
                            "valid_from",
                            "valid_to",
                        ],
                        name="taxes_taxra_jurisdi_e34547_idx",
                    )
                ],
            },
        ),
    ]
